Add capability to retry failed builds
If some package fails to build, it is now possible to fix things and retry.
Also adjust formating of messages printed by script.

diff --git a/build-svn b/build-svn
--- a/build-svn
+++ b/build-svn
@@ -7,9 +7,9 @@ set -o pipefail
 
 build_svn()
 {
-	echo -e "\n*** Start building $1 ($(date +%T)) ***\n" | tee -a "$SBLOG"
+	echo -e "\n=== Start building $1 ($(date +%T)) ===\n" | tee -a "$SBLOG"
 	cd "$1" || return 1 
-	"./$1-svn.SlackBuild" || { echo "Failed to build $1" | tee -a "$SBLOG"; return 1; }
+	"./$1-svn.SlackBuild" || { echo "*** Error: failed to build $1" | tee -a "$SBLOG"; return 1; }
 	echo "Finished building $1 ($(date +%T))" | tee -a "$SBLOG"
 	cd "$SBDIR" || return 1
 	if [[ $ARCH ]]; then
@@ -23,63 +23,77 @@ build_svn()
 
 prompt_exit()
 {
-	read -p "Do you want to continue? [y/N] " SBANS
-	if [[ "$SBANS" != [yY] ]]; then
+	local res
+	read -p "Retry, skip, exit? [r,S,e] " SBANS
+	if [[ "$SBANS" == [eE] ]]; then
 		exit 1
+	elif [[ "$SBANS" == [rR] ]]; then
+		res=0
+	else
+		echo -e "\n*** Skip building $1 ***\n" | tee -a "$SBLOG"
+		res=1
 	fi
 	cd "$SBDIR" || return 1
+	return $res
 }
 
+try_build_svn()
+{
+	while true; do
+		build_svn "$@" || prompt_exit "$1" || break
+	done
+}
 
 echo "[ E17 BUILD START $(date +%T) ]" | tee -a "$SBLOG" || exit 1
 mkdir -p "$SBPKGDIR"
 
 # EFL
-build_svn  eina                  || prompt_exit
-build_svn  eet                   || prompt_exit
-build_svn  evas                  || prompt_exit
-build_svn  evas_generic_loaders  || prompt_exit
-build_svn  ecore                 || prompt_exit
-build_svn  embryo                || prompt_exit
-build_svn  edje                  || prompt_exit
-build_svn  e_dbus                || prompt_exit
-build_svn  efreet                || prompt_exit
-build_svn  eeze                  || prompt_exit
+try_build_svn  eina
+try_build_svn  eet
+try_build_svn  evas
+try_build_svn  evas_generic_loaders
+try_build_svn  ecore
+try_build_svn  embryo
+try_build_svn  edje
+try_build_svn  e_dbus
+try_build_svn  efreet
+try_build_svn  eeze
 
 # Misc. libs and apps
-build_svn  eio                   || prompt_exit
+try_build_svn  eio
 # PROTO/
-build_svn  epdf                  || prompt_exit
-# build_svn  eyesight              || prompt_exit
-build_svn  libeweather           || prompt_exit
-build_svn  emap                  || prompt_exit
-# build_svn  elsa                  || prompt_exit
-build_svn  emotion               || prompt_exit
-build_svn  emprint               || prompt_exit
-build_svn  ethumb                || prompt_exit
-build_svn  elementary            || prompt_exit
-build_svn  ephoto                || prompt_exit
-build_svn  envision              || prompt_exit
-build_svn  exalt                 || prompt_exit
-# build_svn  enjoy                 || prompt_exit
+try_build_svn  epdf
+# try_build_svn  eyesight
+try_build_svn  libeweather
+try_build_svn  emap
+# try_build_svn  elsa
+try_build_svn  emotion
+try_build_svn  emprint
+try_build_svn  ethumb
+try_build_svn  elementary
+try_build_svn  ephoto
+try_build_svn  envision
+try_build_svn  exalt
+# try_build_svn  enjoy
 
 # Enlightenment
-build_svn  enlightenment         || prompt_exit
-build_svn  e_modules-comp-scale  || prompt_exit
-build_svn  e_modules-screenshot  || prompt_exit
-build_svn  e_modules-taskbar     || prompt_exit
-build_svn  e_modules-tiling      || prompt_exit
-build_svn  e_modules-engage      || prompt_exit
-build_svn  e_modules-exalt-client|| prompt_exit
-build_svn  e_modules-eweather    || prompt_exit
-# build_svn  e_modules-mpdule      || prompt_exit
-# build_svn  e_modules-calendar    || prompt_exit
-# build_svn  e_modules-weather     || prompt_exit
+try_build_svn  enlightenment
+try_build_svn  e_modules-comp-scale
+try_build_svn  e_modules-screenshot
+try_build_svn  e_modules-taskbar
+try_build_svn  e_modules-tiling
+try_build_svn  e_modules-engage
+try_build_svn  e_modules-exalt-client
+try_build_svn  e_modules-eweather
+# try_build_svn  e_modules-mpdule
+# try_build_svn  e_modules-calendar
+# try_build_svn  e_modules-weather
+# try_build_svn  eenvader
 # wlan
 
 # Themes
 cd themes
-. themes-svn.build || prompt_exit
+. themes-svn.build
 cd -
 
 # Update dependencies graph
