It's time to move on! Provide SlackBuild for E18.

diff --git a/build-e18 b/build-e18
--- a/build-e18
+++ b/build-e18
@@ -1,16 +1,15 @@
 #!/bin/bash
 
 SBDIR=$(pwd)
-SBPKGDIR="$SBDIR/+packages-git-$(date +%F)"
-SBTHMDIR="$SBDIR/+themes-git-$(date +%F)"
-SBLOG="$SBDIR/build-git-$(date +%F).log"
+SBPKGDIR="$SBDIR/+packages-e18-$(date +%F)"
+SBLOG="$SBDIR/build-e18-$(date +%F).log"
 set -o pipefail
 
-build_package_git()
+build_package()
 {
 	echo -e "\n=== Start building $1 ($(date +%T)) ===\n" | tee -a "$SBLOG"
 	cd "$1" || return 1
-	"./$1-git.SlackBuild" || { echo "*** Error: failed to build $1" | tee -a "$SBLOG"; return 1; }
+	"./$1.SlackBuild" || { echo "*** Error: failed to build $1" | tee -a "$SBLOG"; return 1; }
 	echo "Finished building $1 ($(date +%T))" | tee -a "$SBLOG"
 	cd "$SBDIR" || return 1
 	if [[ $ARCH ]]; then
@@ -20,16 +19,6 @@ build_package_git()
 		upgradepkg --install-new --reinstall $1/$1-*-*-*.txz | tee -a "$SBLOG" || return 1
 		mv $1/$1-*-*-*.txz "$SBPKGDIR" || return 1
 	fi
-}
-
-build_theme_git()
-{
-	echo -e "\n=== Start building $1 ($(date +%T)) ===\n" | tee -a "$SBLOG"
-	cd themes || return 1
-	"./$1-git.build" || { echo "*** Error: failed to build $1" | tee -a "$SBLOG"; return 1; }
-	echo "Finished building $1 ($(date +%T))" | tee -a "$SBLOG"
-	mv *.edj "$SBTHMDIR" || return 1
-	cd "$SBDIR" || return 1
 }
 
 prompt_exit()
@@ -48,10 +37,10 @@ prompt_exit()
 	return $res
 }
 
-try_build_pkg_git()
+try_build_pkg()
 {
 	while true; do
-		build_package_git "$@"
+		build_package "$@"
 		if [[ $? == 0 ]]; then
 			break
 		else
@@ -60,76 +49,28 @@ try_build_pkg_git()
 	done
 }
 
-try_build_thm_git()
-{
-	# ignore errors as themes are not really important
-	local res
-	build_theme_git "$@" || cd "$SBDIR"
-}
-
 echo "[ E18 BUILD START $(date +%T) ]" | tee -a "$SBLOG" || exit 1
 mkdir -p "$SBPKGDIR"
-mkdir -p "$SBTHMDIR"
 
 # EFL
-try_build_pkg_git  efl
-try_build_pkg_git  evas_generic_loaders
-try_build_pkg_git  elementary
-
-# Misc. libs and tools
-try_build_pkg_git  geneet
-try_build_pkg_git  efx
-try_build_pkg_git  esskyuehl
-try_build_pkg_git  libeweather
-try_build_pkg_git  ekbd
+try_build_pkg  efl
+try_build_pkg  evas_generic_loaders
+try_build_pkg  webkit-efl
+try_build_pkg  elementary
 
 # Apps
-try_build_pkg_git  ecrire
-try_build_pkg_git  emprint
-try_build_pkg_git  enjoy
-try_build_pkg_git  entrance
-try_build_pkg_git  ephoto
-try_build_pkg_git  equate
-try_build_pkg_git  maelstrom
-try_build_pkg_git  terminology
+try_build_pkg  terminology
+try_build_pkg  eperiodique
 
 # Developer tools
-try_build_pkg_git  clouseau
-try_build_pkg_git  enventor
-try_build_pkg_git  expedite
+try_build_pkg  expedite
 
 # Games
-try_build_pkg_git  etrophy
-try_build_pkg_git  econcentration
-try_build_pkg_git  efbb
-try_build_pkg_git  elemines
+try_build_pkg  etrophy
+try_build_pkg  elemines
 
 # Enlightenment
-try_build_pkg_git  enlightenment
-try_build_pkg_git  e_modules-alarm
-try_build_pkg_git  e_modules-comp-scale
-try_build_pkg_git  e_modules-engage
-try_build_pkg_git  e_modules-everything-places
-try_build_pkg_git  e_modules-everything-websearch
-try_build_pkg_git  e_modules-eweather
-try_build_pkg_git  e_modules-forecasts
-try_build_pkg_git  e_modules-mpdule
-try_build_pkg_git  e_modules-net
-try_build_pkg_git  e_modules-news
-try_build_pkg_git  e_modules-penguins
-try_build_pkg_git  e_modules-photo
-try_build_pkg_git  e_modules-places
-try_build_pkg_git  e_modules-productivity
-
-# Wallpapers
-try_build_pkg_git  e_modules-eenvader.fractal
-
-# Themes
-try_build_thm_git  23oz
-try_build_thm_git  b_and_w
-try_build_thm_git  darkness
-try_build_thm_git  detourious
-try_build_thm_git  efenniht
+try_build_pkg  enlightenment
 
 # Update dependencies graph
 cd "$SBDIR"
